# Лимитер отключён для приватного инстанса.
# Если включаете limiter: true в settings.yml —
# настройте лимиты здесь.
#
# Документация: https://docs.searxng.org/admin/settings/settings_server.html#settings-server-limiter

[botdetection.ip_limit]
# link_token = false
# filter_link_token = false
# filter_request = false
# limit = 0
